#!/bin/bash

# (C) Copyright IBM Corporation 2016
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

localIP=$(hostname -I | tr -d ' ')

# The mcastaddr below should not be necessary but there is a bug in corosync that requires it
cat > /etc/corosync/corosync.conf <<-EOF
totem {
    version: 2
    cluster_name test
    crypto_cipher: none
    crypto_hash: none
    clear_node_high_bit: yes
    interface {
        ringnumber: 0
        bindnetaddr: $localIP
        mcastaddr: $localIP
        mcastport 5405
    }
    transport: udpu
}
logging {
    fileline: off
    to_syslog: yes
    debug: off
    timestamp: on
    logger_subsys {
        subsys: QUORUM
        debug: off
    }
}
nodelist {
    node {
        ring0_addr: $1
        nodeid: 1
    }
    node {
        ring0_addr: $2
        nodeid: 2
    }
    node {
        ring0_addr: $3
        nodeid: 3
    }
}

quorum {
    provider: corosync_votequorum
}
EOF

service corosync start
service pacemaker start
update-rc.d pacemaker defaults

crm configure property stonith-enabled=false
